### ISSUE TITLE
Change host to 'api.eu.mailgun.net'

### ISSUE THREAD

**Issue by CezarCobuz** [StatelessStudio/ts-mailgun#26]
If I was using [mailgun-js](https://www.npmjs.com/package/mailgun-js) the host could be easily be set. The documentation states that for EU it should be: 

> host - the mailgun host (default: 'api.mailgun.net'). Note that if you are using the EU region the host should be set to 'api.eu.mailgun.net'

Without this I get 

> Error: Domain not found

**Comment by DrewImm** [comment]
Thanks, will add `host` parameter

**Comment by DrewImm** [comment]
Moved to [Issue #27]

**Comment by DrewImm** [comment]
@CezarCobuz 
This has been resolved. You may now set custom options, such as host:

```typescript
mailer.options = {
	host: 'api.eu.mailgun.net'
};
```

**Make sure to set your options before calling init()**

See the entire example for custom options: https://github.com/StatelessStudio/ts-mailgun#mailgun-options
