### ISSUE TITLE
Installation/configuration of this module causes multiple compile errors in Ionic 4 project

### ISSUE THREAD

**Issue by ceaheart** [StatelessStudio/ts-mailgun#33]
I have added this module to my Ionic 4 project, and once I do, I am presented with multiple compile errors.  I do nothing else but add the module to my project and then add the code, per the documentation, to one of my pages.

ERROR in ./node_modules/get-uri/data.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\Chris\TestProject\node_modules\get-uri'
ERROR in ./node_modules/mailgun-js/lib/mailgun.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\Chris\TestProject\node_modules\mailgun-js\lib'
ERROR in ./node_modules/pac-proxy-agent/index.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\Chris\TestProject\node_modules\pac-proxy-agent'
ERROR in ./node_modules/tsscmp/lib/index.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\Chris\TestProject\node_modules\tsscmp\lib'
ERROR in ./node_modules/pac-resolver/dnsResolve.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\Chris\TestProject\node_modules\pac-resolver'
ERROR in ./node_modules/pac-resolver/isResolvable.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\Chris\TestProject\node_modules\pac-resolver'
ERROR in ./node_modules/pac-resolver/isInNet.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\Chris\TestProject\node_modules\pac-resolver'
ERROR in ./node_modules/socks-proxy-agent/index.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\Chris\TestProject\node_modules\socks-proxy-agent'
ERROR in ./node_modules/ftp/lib/connection.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Chris\TestProject\node_modules\ftp\lib'
ERROR in ./node_modules/get-uri/file.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Chris\TestProject\node_modules\get-uri'
ERROR in ./node_modules/mailgun-js/lib/request.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Chris\TestProject\node_modules\mailgun-js\lib'
ERROR in ./node_modules/ts-mailgun/ts-mailgun.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Chris\TestProject\node_modules\ts-mailgun'
ERROR in ./node_modules/get-uri/http.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\Chris\TestProject\node_modules\get-uri'
ERROR in ./node_modules/mailgun-js/lib/request.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\Chris\TestProject\node_modules\mailgun-js\lib'
ERROR in ./node_modules/proxy-agent/index.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\Chris\TestProject\node_modules\proxy-agent'
ERROR in ./node_modules/agent-base/patch-core.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\agent-base'
ERROR in ./node_modules/get-uri/https.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\get-uri'
ERROR in ./node_modules/get-uri/http.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\get-uri'
ERROR in ./node_modules/mailgun-js/lib/request.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\mailgun-js\lib'
ERROR in ./node_modules/pac-proxy-agent/node_modules/https-proxy-agent/node_modules/agent-base/patch-core.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\pac-proxy-agent\node_modules\https-proxy-agent\node_modules\agent-base'
ERROR in ./node_modules/proxy-agent/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\proxy-agent'
ERROR in ./node_modules/proxy-agent/node_modules/https-proxy-agent/node_modules/agent-base/patch-core.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\Chris\TestProject\node_modules\proxy-agent\node_modules\https-proxy-agent\node_modules\agent-base'
ERROR in ./node_modules/ftp/lib/connection.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\ftp\lib'
ERROR in ./node_modules/http-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\http-proxy-agent'
ERROR in ./node_modules/pac-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\pac-proxy-agent'
ERROR in ./node_modules/pac-proxy-agent/node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\pac-proxy-agent\node_modules\https-proxy-agent'
ERROR in ./node_modules/pac-resolver/myIpAddress.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\pac-resolver'
ERROR in ./node_modules/proxy-agent/node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\proxy-agent\node_modules\https-proxy-agent'
ERROR in ./node_modules/socks/build/client/socksclient.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\socks\build\client'
ERROR in ./node_modules/socks/build/common/helpers.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Chris\TestProject\node_modules\socks\build\common'
ERROR in ./node_modules/ip/lib/ip.js
Module not found: Error: Can't resolve 'os' in 'C:\Users\Chris\TestProject\node_modules\ip\lib'
ERROR in ./node_modules/file-uri-to-path/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Chris\TestProject\node_modules\file-uri-to-path'
ERROR in ./node_modules/get-uri/ftp.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Chris\TestProject\node_modules\get-uri'
ERROR in ./node_modules/ftp/lib/parser.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Chris\TestProject\node_modules\ftp\lib'
ERROR in ./node_modules/ftp/node_modules/readable-stream/readable.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Chris\TestProject\node_modules\ftp\node_modules\readable-stream'
ERROR in ./node_modules/ftp/node_modules/readable-stream/lib/_stream_writable.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Chris\TestProject\node_modules\ftp\node_modules\readable-stream\lib'
ERROR in ./node_modules/ftp/node_modules/readable-stream/lib/_stream_readable.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Chris\TestProject\node_modules\ftp\node_modules\readable-stream\lib'
ERROR in ./node_modules/mailgun-js/lib/request.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Chris\TestProject\node_modules\mailgun-js\lib'
ERROR in ./node_modules/socks/build/common/helpers.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Chris\TestProject\node_modules\socks\build\common'
ERROR in ./node_modules/ftp/lib/connection.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Chris\TestProject\node_modules\ftp\lib'
ERROR in ./node_modules/http-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Chris\TestProject\node_modules\http-proxy-agent'
ERROR in ./node_modules/pac-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Chris\TestProject\node_modules\pac-proxy-agent'
ERROR in ./node_modules/pac-proxy-agent/node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Chris\TestProject\node_modules\pac-proxy-agent\node_modules\https-proxy-agent'
ERROR in ./node_modules/proxy-agent/node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Chris\TestProject\node_modules\proxy-agent\node_modules\https-proxy-agent'
ERROR in ./node_modules/socks-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Chris\TestProject\node_modules\socks-proxy-agent'
ERROR in ./node_modules/pac-resolver/index.js
Module not found: Error: Can't resolve 'vm' in 'C:\Users\Chris\TestProject\node_modules\pac-resolver'
ERROR in ./node_modules/ftp/lib/connection.js
Module not found: Error: Can't resolve 'zlib' in 'C:\Users\Chris\TestProject\node_modules\ftp\lib'
[ERROR] An error occurred while running subprocess ng.

**Comment by DrewImm** [comment]
This library should not be used directly from an Ionic project. This is due to the fact that a private Mailgun API key is required - and that must not be included in the front-end!

Having your API key on a front-end client will expose it to potential attackers.

Instead, you should include ts-mailgun on a remote API server which authenticates separately with the front-end client.

Hope this helps
