### ISSUE TITLE
Multiple Tags

### ISSUE THREAD

**Issue by JannikZed** [StatelessStudio/ts-mailgun#40]
Hi there,

Is there a way to set multiple tags for an Email? I was just successful using one tag.

**Comment by DrewImm** [comment]
Please see https://documentation.mailgun.com/en/latest/api-tags.html#tags and https://documentation.mailgun.com/en/latest/user_manual.html#tagging.

Accoridng to Mailgun, up to 3 tags are supported. See the above URL for an example

This should be achievable using [Generic Requests](https://github.com/StatelessStudio/ts-mailgun#generic-requests) in ts-mailgun.

This package does not include any tag functionality, as it is a wrapper over Mailgun
